### ISSUE TITLE
how to deal with pedestrian or some insane npc

### ISSUE THREAD

**Issue by ZOUYIyi** [HKUST-Aerial-Robotics/EPSILON#14]
in the paper, it assumes npc car will pursuit the lane, it is right in most of cases， but sometimes it is not  , such as  pedestrian want to cross the road，or a insane npc who don't care lane at all ,what will ego acting to this?

**Comment by MasterIzumi** [comment]
@ZOUYIyi That is true in the real-world application. I think the key point is how to model and predict/update the "intention" of the surrounding agents. Since we mostly consider highway scenarios in our experiments, vehicles driving w.r.t. lanes is a reasonable assumption in most of the cases. To handle the abnormal behavior, you can design extra intentions (hidden states) to represent them and infer their probabilities using perception results. Then, these probabilities can be used in the guided observation branching (in EPSILON). It will cost much more computation if the dimension of the hidden state increases, so I personally think introducing an anomaly detection module may be a better approach. Therefore the pipeline can be: anomaly detection using observed data -> determine potential intentions for each agent -> MPDM/EPSILON pipeline (or other POMDP-based methods). 

As for the pedestrian, we have to design an interactive model for them. It may contain several hidden states to represent the "intentions" or "aggressiveness" which can be updated during planning. For pedestrian modeling, you can refer to:
1) Bai, Haoyu, et al. "Intention-aware online POMDP planning for autonomous driving in a crowd." 2015 IEEE international conference on robotics and automation. IEEE, 2015.
1) Luo, Yuanfu, et al. "Porca: Modeling and planning for autonomous driving among many pedestrians." IEEE Robotics and Automation Letters 3.4 (2018): 3418-3425.
2) Cai, Panpan, et al. "Lets-drive: Driving in a crowd by learning from tree search." arXiv preprint arXiv:1905.12197 (2019).

**Comment by ZOUYIyi** [comment]
@MasterIzumi 
thank you for your reply , i will read these paper to find out.
