### ISSUE TITLE
Can this solution constrain the curvature of the trajectory?

### ISSUE THREAD

**Issue by zhumingpassional** [HKUST-Aerial-Robotics/EPSILON#16]
Can this solution constrain the curvature of the trajectory? If, how to solve it? otherwise, why? Thank you.

**Comment by MasterIzumi** [comment]
@zhumingpassional 
For the behavior planning layer, the answer is yes. That is because the forward simulation depends on the internal controller/motion model, if the controller is feasible in terms of kinematics and dynamics, the results will not violate the curvature constraint (same for lateral/longitudinal velocity/acceleration constraints).
For the motion planning layer (SSC planner), since we perform planning in the Frenet frame and decouple the lateral and longitudinal axes, it can not restrict the curvature directly. However, the initial solution from the behavior layer is guaranteed to be feasible, and we add a 'similarity cost' in the optimization, therefore, the output trajectory is feasible most of the time.
