### ISSUE TITLE
where is the road  boundry

### ISSUE THREAD

**Issue by ZOUYIyi** [HKUST-Aerial-Robotics/EPSILON#7]
I read the code and there are some questions I can't understand.
in the file ssc_map.cc , function  **SscMap::ConstructSscMap** use  _obstacle_grids_ to build static part of _p_3d_grid_，but I can't find where the lane boundry transform to _obstacle_grids_, Can you give me a hint ?

**Comment by MasterIzumi** [comment]
@ZOUYIyi 
Hi, sorry for the late reply.
In our implementation, the lane boundary is not used in the construction of SscMap. Actually, since this is a very simplified simulator, the map info in also limited. The only thing we have is the centerline of a lane, and we assume all lanes have a fixed width (e.g., 3.8 meters).

**Comment by ZOUYIyi** [comment]
@MasterIzumi 
thanks for your reply
